/* Automatically generated by './build/bin/build-entry.js' */

import CEditor from "./CEditor/index.js";
import CFormModal from "./CFormModal/index.js";
import CIcon from "./CIcon/index.js";
import CMap from "./CMap/index.js";
import CTable from "./CTable/index.js";
import CUpload from "./CUpload/index.js";
const components = [CEditor, CFormModal, CIcon, CMap, CTable, CUpload];

const install = function (Vue, opts = {}) {
  Vue.prototype.$baseUrl = opts.baseUrl;
  Vue.prototype.$serviceUrl = opts.serviceUrl;
  components.forEach((component) => {
    Vue.component(component.name, component);
  });
};

/* istanbul ignore if */
if (typeof window !== "undefined" && window.Vue) {
  install(window.Vue);
}

export default {
  version: "0.1.35",
  install,
  CEditor,
  CFormModal,
  CIcon,
  CMap,
  CTable,
  CUpload,
};
